# Site
name: "Rovel Blog"
title: "Rovel Blog"
description: "Read all the news 📰 from our Rovel Bloggers!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'rovel-blog'
mailchimp-list: 'https://rovelstars.us2.list-manage.com/subscribe/post?u=95fd1830dc5c9ba4d505fbd9a&amp;id=1ba287df95'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sayantan:
    name: sayantan
    display_name: Sayantan    
    avatar: 'https://cdn.discordapp.com/avatars/602902050677981224/b52dbee2e30b48743e1c17be9c6b17f2.png?size=1024'
    email: rovelstars300@gmail.com
    web: https://rovelstars.ga
    twitter: https://twitter.com/sayanta123
    description: "Hey there! Im the owner of Rovel Stars!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
